//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IModelService")]
    public interface IModelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetEmployeeList", ReplyAction="http://tempuri.org/IModelService/GetEmployeeListResponse")]
        MyEF.Models.Employee[] GetEmployeeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModelService/GetEmployeeList", ReplyAction="http://tempuri.org/IModelService/GetEmployeeListResponse")]
        System.Threading.Tasks.Task<MyEF.Models.Employee[]> GetEmployeeListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelServiceChannel : TestConsole.ServiceReference1.IModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelServiceClient : System.ServiceModel.ClientBase<TestConsole.ServiceReference1.IModelService>, TestConsole.ServiceReference1.IModelService {
        
        public ModelServiceClient() {
        }
        
        public ModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MyEF.Models.Employee[] GetEmployeeList() {
            return base.Channel.GetEmployeeList();
        }
        
        public System.Threading.Tasks.Task<MyEF.Models.Employee[]> GetEmployeeListAsync() {
            return base.Channel.GetEmployeeListAsync();
        }
    }
}
